config/routes.rb
Webdw::Application.routes.draw do
  resources :galleries do
    resources :videos, :only => [:show]
  end

  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :staff
  resources :blog do
    post 'create_comment'
  end

  resources :home do
    collection do
      get :services
      get :portfolio
      get :portfolio2
      get :portfolio3
      get :contact
      get :staff
    end
  end

  root :to => 'home#index'
  match ':controller(/:action(/:id(.:format)))'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :medias, :as => :mediable, :dependent => :destroy
  has_many :photos, :as => :mediable, :dependent => :destroy
  has_many :videos, :as => :mediable, :dependent => :destroy
  accepts_nested_attributes_for :medias, :allow_destroy => true
  accepts_nested_attributes_for :photos, :allow_destroy => true
  accepts_nested_attributes_for :videos, :allow_destroy => true

  default_scope order("created_at ASC")

  def to_s
    self.title
  end

  def self.default_gallery(title="demo reel")
    self.find_by_title(title)
  end

  def last_video
    self.videos.last
  end
end

app/models/media.rb
class Media < ActiveRecord::Base
  set_table_name "media"
  belongs_to :gallery
  has_attached_file :photo, :styles => {:medium =>"356x185!", :thumb => "100x100>", :blog => "301x185!"}

  belongs_to :mediable, :polymorphic => true
end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :contact_how, :message

  validates :name, :email, :message, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, :use => :slugged

  acts_as_taggable_on :tags
  acts_as_taggable_on :blogs

  has_many :medias, :as => :mediable, :dependent => :destroy
  has_many :photos, :as => :mediable, :dependent => :destroy
  has_many :videos, :as => :mediable, :dependent => :destroy

  accepts_nested_attributes_for :medias, :allow_destroy => true
  accepts_nested_attributes_for :photos, :allow_destroy => true
  accepts_nested_attributes_for :videos, :allow_destroy => true
  scope :all_pages, self.tagged_with(["about","services","staff"], :on => :tags, :any => true).order('created_at DESC')
  scope :about, self.tagged_with("about", :on => :tags).order("created_at DESC")
  scope :services, self.tagged_with("services", :on => :tags).order("created_at ASC")
  scope :staff, self.tagged_with("staff", :on => :tags).order("orden ASC")

  def last_photo_url(size = nil)
    begin
      photos.last.photo.url(size)
    rescue Exception => exc
      nil
    end
  end

  def last_video_url
    begin
      videos.last.url
    rescue Exception => exc
      nil
    end
  end
end

app/models/photo.rb
class Photo < Media
  set_table_name "media"
  default_scope :conditions =>{:type_media => false}
end

app/models/post.rb
class Post < Page
  default_scope self.tagged_with(['blog'], :on => :tags, :any=>true).order('created_at DESC')
  has_many :comments, :as => :commentable
end

app/models/video.rb
class Video < Media
  set_table_name "media"
  default_scope :conditions =>{:type_media => true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def create_comment
    @post = Post.find(params[:blog_id])
    @comment = Comment.new(params[:comment])
    @comment.commentable = @post

    respond_to do |wants|
      if @comment.save
        flash[:notice] = 'Comment was successfully created.'
        wants.html { redirect_to(:back) }
      else
        wants.html { render :action => "show" }
      end
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      Notifications.new_message(@message).deliver
      redirect_to({:action => 'contact', :controller =>'home'}, :notice => "Message was successfully sent.")
    else
      flash[:alert] = "Please fill all fields."
      render 'home/contact'
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def show
    @galleries = Gallery.all
    @gallery = Gallery.find(params[:id])
    @titulo = "Gallery #{@gallery.title}"
    @videos_galeria = @gallery.videos
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @titulo = "Home Page - Zenlabs.net"
    @pages = Page.staff
    @gallery = Gallery.all
    @blog = Post.all
  end
  def services
    @titulo = "Services"
    @services = Page.services
  end
  def portfolio
    @titulo = "Portfolio"
    @galleries = Gallery.all
    @gallery = Gallery.default_gallery
    @video = @gallery.last_video if @gallery
  end
  def portfolio1
    @titulo = "Portfolio"
  end
  def portfolio2
    @titulo = "Portfolio"
    @galleries = Gallery.all
  end
  def portfolio3
    @titulo = "Portfolio"
  end
  def staff
    @titulo = "Staff"
  end
  def blog1
    @titulo = "Blog"
  end
  def contact
    @titulo = "Contact"
    #@message = Message.new
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

end

app/controllers/staff_controller.rb
class StaffController < ApplicationController
  def index
    @staff = Page.staff
  end

  def show
    @staff = Page.staff.find(params[:id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show
    @galleries = Gallery.all
    @gallery = Gallery.find(params[:gallery_id])
    @video = Video.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_video(url)
    begin
      ::UnvlogIt.new(url)
    rescue Exception
      nil
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admin/galleries/_form.html.haml
= semantic_form_for [:admin, @gallery], :html =>{ :multipart => true} do |f|
  = f.inputs "Gallery Photos" do
    = f.input :title
    = f.input :description

    = f.semantic_fields_for :photos do |photo|
      = render "photo_fields", :f => photo
    = f.semantic_fields_for :videos do |video|
      = render "video_fields", :f => video
    .links
      = link_to_add_association 'Add photo file', f, :photos
      = link_to_add_association 'Add video file', f, :videos
  = f.buttons

app/views/admin/galleries/_photo_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :photo, :as => :file
    - unless f.object.new_record?
      = image_tag f.object.photo.url(:thumb)
    = link_to_remove_association "remove photo", f

app/views/admin/galleries/_video_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :url
    - if !f.object.new_record? && videotron = get_video(f.object.url)
      = image_tag videotron.thumbnail
    = link_to_remove_association "remove video", f

app/views/admin/photos/_form.html.haml
= semantic_form_for [:admin, @photo], :html =>{ :multipart => true} do |f|
  = f.inputs "Photos" do
    /= f.input :gallery
    = f.input :photo, :as => :file
  = f.buttons

app/views/admin/photos/_show.html.haml
= @photo.id
= @photo.gallery
= image_tag @photo.photo.url(:thumb)

app/views/admin/videos/_form.html.haml
= semantic_form_for [:admin, @video] do |f|
  = f.inputs "Photos" do
    /= f.input :gallery
    = f.input :url
  = f.buttons

app/views/admin/videos/_show.html.haml
- if videotron = get_video(@video.url)
  %h3= videotron.title
  %h2= videotron.service
  %p= image_tag (videotron.thumbnail)
  %p= videotron.embed_html.html_safe

app/views/blog/index.html.haml
:javascript
  $(document).ready(function(){
     $("#bodywrapper").css({'background-color' : '#c9ced2', 'margin' : '127px 0 0'});
     $("#pagecomment").html("BlogTemas de interés para todos");
  });
:css
  #mainblogleft{
  	float:left;
      margin: 180px 0 0 100px;
      width: 575px;
  	font-family:arial;
  	font-size:15px;
  }
  	.blogtitle{
  		font-size:22px;
  		font-family:arial;
  		font-weight:bold;
  		color:#2e568a;
  	}
  	.bloginfo{
  		font-size:14px;
  		font-family:arial;
  		font-weight:lighter;
  		color:#999;
  	}
  	.blogseparator{
  		float: left;
  		height: 40px;
  		margin: 30px 0 0 45px;
  		width: 485px;
  	}
  		.blogseparatorline{
  			background-image: url("img/blogsepaatorline.png");
  			background-repeat: repeat-x;
  			float: left;
  			height: 3px;
  			width: 216px;
  		}
  		.blogseparatorlogo{
  			background-image: url("img/zenlabsiconblogseparatot.png");
  			background-repeat: no-repeat;
  			float: left;
  			height: 33px;
  			margin: -15px 5px 0 10px;
  			width: 30px;
  		}
  #mainblogright{
      float: left;
      margin: 175px 0 0 93px;
      width: 222px;
  }
  	.blogrightheader{
  		width: 220px;
  		height:55px;
  		background-color:#b1b6bc;
  		-webkit-border-top-left-radius: 18px;
  		-webkit-border-top-right-radius: 18px;
  		-moz-border-radius-topleft: 18px;
  		-moz-border-radius-topright: 18px;
  		border-top-left-radius: 18px;
  		border-top-right-radius: 18px;
  		color:#000;
  		font-family:arial;
  		font-weight:bold;
  		font-size:18px;
  		text-align:center;
  		line-height:3em;
  	}
  	.blogrightcontainer{
  		background-image:url(img/logorightgrill.png);
  		width:220px;
  		height:358px;
  		background-repeat:repeat-x;
  	}
  		.blogrighttext{
  			font-family:Arial;
  			font-size:12px;
  			color:#000;
  			margin:0 22px 8px 22px;
  			cursor:pointer;
  		}
  		.blogrighttext:hover{
  			color:#3B82C4;
  			text-decoration:underline;
  		}
#mainblogleft
  - @posts.each do |blog|
    .blogtitle
      =blog.title
    .bloginfo
      ="posteado por: #{} | #{blog.created_at.strftime("%d de %m del %Y")} | 12 Comentarios"
    %br/
    =blog.content
    %br/
    %br/
    /.blogseparator
    /.blogseparatorline
    /.blogseparatorlogo
    /.blogseparatorline
#mainblogright{:style => "z-index:50000;"}
  .blogrightheader Últimas entradas
  .blogrightcontainer
    .blogrighttext Un Job Borad para ayudar.
    .blogrighttext Las certificaciones debieran mori, Haz tu parte
    .blogrighttext Presentación Java Day:"Ruby, Programando para Humanos"
    .blogrighttext Presentación Java Day:"El lado cool de java"
    .blogrighttext De orador en el "Java day", auspiciado por el INACAP de Osorno Pasión
    .blogrighttext El inglés es una habilidad que puedes aprender (rápido!)
    .blogrighttext Posteando doble
  %br/
  .blogrightheader Archivos
  .blogrightcontainer
    .blogrighttext June 2011 (8)
    .blogrighttext March 2011 (1)
    .blogrighttext January 2011 (1)
    .blogrighttext November 2010 (1)
    .blogrighttext October 2010 (3)
    .blogrighttext August 2010 (1)
    .blogrighttext July 2010 (2)
    .blogrighttext June 2010 (1)
    .blogrighttext May 2010 (7)
    .blogrighttext April 2010 (2)
    .blogrighttext march 2010 (8)
    .blogrighttext February 2010 (5)

app/views/blog/show.html.haml
#comments.scroll-pane-os.grid_7
  .scrollbar
    .track
      .thumb
        .end
  .viewport
    .overview
      %p.titulo_blog
        = @post.title
        %br/
        %span.date= @post.created_at.strftime('%d/%m/%Y')
      %br/
      .clear
      %p.gris= raw sanitize(textilize(@post.content))
      %br/
      - for image in @post.photos
        = image_tag image.photo.url(:blog), :alt => @post.title, :height => "185", :width => "301"
      - for video in @post.videos
        - if videotron = get_video(video.url)
          = raw videotron.embed_html(489, 325)
      %br/
      %strong Tags:
      = @post.blog_list
      %br/
      .clear
      .number_coments
        %p= pluralize(@post.comments.length, "Comment")
      - if @post.comments.empty?
        .comment
          %p No comments.
      - else
        - for comment in @post.comments
          .coment
            %p.titulo_blog= comment.name
            %p.date_coment= comment.created_at.strftime('%d/%m/%Y')
#img_rigth.grid_4
  %p.title_fom_blog Post your comment ;)
  = form_for(Comment.new, :url => blog_create_comment_path(@post)) do |f|
    #content_form_left
      %label.label Nombre:
      %br
      %label.label E-mail:
      %br
      %label.label Website:
      %br
      %label.label Message:
    #content_form_right
      = f.text_field :name,    :class => 'input_post'
      = f.text_field :email,   :class => 'input_post'
      = f.text_field :website, :class => 'input_post'
      = f.text_area  :comment, :cols => '25', :rows => '4', :class => 'input_post_message'
    %br
    = submit_tag 'Post comment', :class => 'btn padding_right'

:javascript
  $(function()
    {
      $('.scroll-pane-os').jScrollPane(
        {
          showArrows: true,
          verticalArrowPositions: 'os'
          //horizontalArrowPositions: 'os'
        }
        );
    });

app/views/home/_blog.html.haml
#bodybottomright
  .blogmaincontainer
    .blogcontainer
      - @blog.each do |blog|
        %span.blogmessagetitle= blog.title
        %br
        %span.blogmessagedate= "Posteado el #{blog.created_at.strftime("%d-%m-%Y")}"
        %br
        %img{:src=>"../images/blogseparator.png", :width=>"216", :height=>"1"}
        %br
    %div
      .bloglastaccessrow
      .lastaccess &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Entradas anteriores

app/views/home/_media.html.haml
%div{:style=>"float:left; width:444px;"}
  %div{:style=>"background-image:url(../images/bodybottomrighttop.png); width:360px; height:33px; margin:31px 0px 0px 82px; position:absolute;"}
  %div{:style=>"background-image:url(../images/bodybottomleft.png); position:absolute; width:443px; height:450px; background-repeat:no-repeat;"}
  .teammediacontainers
    %div{ :style=>"float:right; margin:179px 75px 0 0; font-size:18px;", :class=>"menutextblue"}
      Ver todas
      %br
      las fotos
      %br
      %img{:src=>"../images/seeallpictures.png", :width=>"11", :height=>"14"}
  %div{:id=>"whatdowedo", :style=>"margin:126px 0 0 70px;"}
    %div{:class=>"pagecomment", :style=>"font-size:27px;"}
      Qu&eacute; hacemos?
    %div{:style=>" font-size: 11px;", :class=>"pagecomment"}
      Gastamos nuestro tiempo resolviendo tus problemas o
      %br
      investigando c&oacute;mo hacerlo con calidad en el menor tiempo posible.
    .techinfo
      %img{ :src=>"../images/rails.png", :width=>"35", :height=>"45"}
      %span{:class=>"techname"}
        Ruby on Rails
    .techinfo
      %img{:src=>"../images/php.png", :width=>"60", :height=>"32"}
      %span.techname
        PHP
    .techinfo
      %img{:src=>"../images/wordpress.png", :width=>"34", :height=>"34"}
      %span.techname
        Wordpress
    .techinfo
      %img{:src=>"../images/drupal.png", :width=>"31", :height=>"35"}
      %span.techname
        Drupal

app/views/home/_staff.html.haml
#developinfoleft
  #developinfofaces
    - @pages.each do |staff|
      .developerinfofacebox{:dev=>"#{staff.id}"}
        = image_tag staff.last_photo_url, :size=>"26x29"
  #developinfobubbles
  #developinfopicture
#developinforight
  #developinforightcontainer1
  #developinforightcontainer2
  #developinfotextcontainer
    #developername.pagecomment
    - @pages.each do |profile|
      = profile.title
      #developerrange
        = profile.subtitle
      #developercomment
        = profile.content
      #medailcontainer
        .frameworkicon
        .frameworkicon
        .frameworkicon
        .frameworkicon
        .frameworkicon
%br
#bodyseparator

:javascript
  function setdevelopersinfo(){
    /*Set developer info*/
    developersinfoarray=new Array;
    developersinfoarray[0]=new Array("url('../images/dev.png')","jose luis","Developer","XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX ...","");
    developersinfoarray[1]=new Array("url('../images/picturedeveloper1.png')","Abraham Barrera","Desarrollador","Desde pequeño le gustó crear cosas, y ...","");

    /*Set developer medails*/
    developermeadils=new Array;
    developermeadils[0]=new Array("php","sql");
    developermeadils[1]=new Array("php","ruby","sql");
  }
  function medails(developercode){
    var strmedails="";
    for (var i=0; i<=((developermeadils[developercode].length)-1); i++){
      strmedails+="<div class='frameworkicon'>"+developermeadils[developercode][i]+"</div>";
    }
    $("#medailcontainer").html(strmedails);
  }
  $(document).ready(function(){
    setdevelopersinfo();
             /*$("#bodywrapper").css({'background-color' : '#2c5283', 'margin' : '127px 0 0'});
             $("#pagecomment").html("Contactanos<br>");	*/
    $("#bodywrapper").css("height","1410px");

    $(".developerinfofacebox").click(function(){

      $("#developinfopicture").css("background-image",developersinfoarray[$(this).attr("dev")][0]);

      $("#developername").html(developersinfoarray[$(this).attr("dev")][1]);
      $("#developerrange").html(developersinfoarray[$(this).attr("dev")][2]);
      $("#developercomment").html(developersinfoarray[$(this).attr("dev")][3]);

      medails($(this).attr("dev"));

    });
  });

app/views/home/contact.html.haml
:javascript
  $(document).ready(function(){
     $("#bodywrapper").css({'background-color' : '#2c5283', 'margin' : '127px 0 0'});
     $("#pagecomment").html("Contactanos");
     $("#bodywrapper").css("height","714px");
  });
#contactcontainer
  .skybluetext ¿Listo para contratarnos?
  #googlemapcontainer
    %iframe{:frameborder => "0", :height => "350", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => "http://maps.google.com/maps/ms?mpa=0&ctz=300&mpf=3&ie=UTF8&t=m&vpsrc=6&source=embed&num=10&msa=0&sll=37.0625,-95.677068&sspn=23.875,57.630033&msid=206930595307460980872.0004ae0140afb3c870835&ll=-16.506788,-68.130512&spn=0.028803,0.036478&z=14&output=embed", :width => "425"}
  #contactusinfocontainer
    #contactusleft.skybluetext Email Teléfonos Dirección
    #contactuscenter
    #contactusright.whitetext info@zenlabs.com (591)-2424567 ι (591)-2435556 Direccion de ejemplo

app/views/home/index.html.haml
= render "home/staff"
= render "home/media"
= render "home/blog"

app/views/home/index_old.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.erb

app/views/home/portfolio.html.haml
#left_menu.grid_3
  %ul
    = render @galleries, :gs => @gallery
- if @video
  #player_video.grid_7
    - if videotron = get_video(@video.url)
      = raw videotron.embed_html(489, 325)
    %br/
    %br/
    %p
      Client:
      %strong AXTEL
    %p
      Add Name:
      %strong Axtel Extension IP
    %p
      Date:
      %strong 10.05.2011

app/views/home/portfolio2.html.haml
#left_menu.grid_3
  %ul
    %li
      %a{:href => "#"} Institutional Spots
    %li
      %a{:href => "#"} Promotonial Spots
    %li
      %a{:href => "#"} Corporate Videos
    %li
      %a{:href => "#"} Demo Reals
    %li
      %a{:href => "#"} Just for fun
#back.grid_8
  %a{:href => "#"}
    %img{:alt => "video", :height => "62", :src => "../images/bg_video_mini.png", :width => "80"}/
  %a{:href => "#"}
    %img{:alt => "video", :height => "62", :src => "images/bg_video_mini.png", :width => "80"}/
  %a{:href => "#"}
    %img{:alt => "video", :height => "62", :src => "images/bg_video_mini.png", :width => "80"}/
  %a{:href => "#"}
    %img{:alt => "video", :height => "62", :src => "images/bg_video_mini.png", :width => "80"}/
  %a{:href => "#"}
    %img{:alt => "video", :height => "62", :src => "images/bg_video_mini.png", :width => "80"}/
  %a{:href => "#"}
    %img{:alt => "video", :height => "62", :src => "images/bg_video_mini.png", :width => "80"}/
  %a{:href => "#"}
    %img{:alt => "video", :height => "62", :src => "images/bg_video_mini.png", :width => "80"}/
  %a{:href => "#"}
    %img{:alt => "video", :height => "62", :src => "images/bg_video_mini.png", :width => "80"}/

app/views/home/services.html.haml
%script{:src => "js/jquery.cycle.all.js", :type => "text/javascript"}

#worktitledesc
  #worktitlecontainer
    .worktitle.menutextblue
    .workdesc
.worksimagecontainer
  #workimages
    %img{:comment => "Cuponix aggregates and recommends the best daily deals of the most of chilean cities. We aggregate the best dailydeals from the majority of the coupons sites such as Groupon.", :desc => "Rails, Ux, Facebook Api, Web Scraping", :height => "320", :src => "../images/agonica.jpg", :title => "CUPONIX", :width => "320"}/
    %img{:comment => "guitar guitar guitar guitar guitar guitar guitar guitar guitar guitar ", :desc => "fgfgfgfgfgfgfgfgfgfgfgfgf: my preferences: the best guitar: Ibañez", :height => "320", :src => "../images/guitar1.jpg", :title => "GUITAR 1", :width => "320"}/
    %img{:comment => "guitar 2 guitar 2 guitar 2 guitar 2 guitar 2 guitar 2 guitar 2 guitar 2 guitar 2 guitar 2 guitar 2 guitar 2", :desc => " fgfgfgfgfgfgfgfgfgfgfgfgf: my preferences: another ibañez guitar", :height => "382", :src => "../images/guitar2.jpg", :title => "GUITAR 2", :width => "500"}/
    %img{:comment => "developer developer developer v v v v developerdeveloperdeveloper developer developer developer developer developer developer developer vdeveloper developer developer", :desc => "fgfgfgfgfgfgfgfgfgfgfgfgf:  comment: this is a developer standar", :height => "335", :src => "../images/picturedeveloper2.png", :title => "DEVELOPER", :width => "290"}/
.workimagesselector
  #nav.nav.navigator
#imagetextcontainer
  .workimagetext

:javascript
  $(document).ready(function(){
     $("#pagecomment").html("Nuestros Trabajos");
  });
  $('#workimages').cycle({
          fx:     'fade',
          speed:  'slow',
          speed:    300,
          timeout:  5000,
          pager:  '#nav',
          after:   onAfter
  });
  function onAfter() {
          $(".worktitle").html($(this).attr("title"));
          $(".workdesc").html($(this).attr("desc"));
          $(".workimagetext").html($(this).attr("comment"));
  }

app/views/staff/show.html.haml
#text_left.grid_4
  %h1
    = @staff.title
    %br
    %span
      = @staff.subtitle
  %p= @staff.content

#about_image.grid_7
  = image_tag @staff.last_photo_url, :height => "542", :width => "464", :alt => @staff.title

app/views/videos/show.html.haml
#left_menu.grid_3
  %ul
    = render @galleries, :gs => @gallery
#player_video.grid_7
  - if videotron = get_video(@video.url)
    = raw videotron.embed_html(489, 325)
  %br/
  %br/
  %p
    Client:
    %strong AXTEL
  %p
    Add Name:
    %strong Axtel Extension IP
  %p
    Date:
    %strong 10.05.2011